##
##  VCS -- Worktree Management for Git Version Control System
##  Copyright (c) 2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under MIT <https://spdx.org/licenses/MIT>
##

#   [tool] static code analysis (linting)
lint
    eslint --config eslint.mjs vcs.ts

#   [tool] build entire project
build : lint build-cmd

#   [tool] build command program
build-cmd
    tsc

#   [tool] remove regularly built files
clean
    shx rm -rf dst

#   [tool] remove all built files
distclean : clean
    shx rm -f package-lock.json
    shx rm -rf node_modules

